
name: Discord Webhook

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  page_build:
  release:
    types: [published, created]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Discord Webhook
        uses: bythope/discord-webhook@master
        with:
          webhookUrl: ''
          handler: 'release'
