
name: Discord Webhook

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  page_build:
  release:
    types:
      - '*'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Discord Webhook
        uses: bythope/discord-webhook@master
        with:
          webhookUrl: 'https://discordapp.com/api/webhooks/765922924540198933/nDp4Tu_uJotrm739NrMXupOgpNq1oma8URT8ZbkZMbLNFin5nIPWyhcBxIIwXc9nb6_C'
          handler: 'release'
