name: Discord Webhook Messages
on:
  push:
    branches: ['master']
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Discord Webhook
        uses: filipkule/discord-webhook-messages@master
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          handler: 'push'
